name: Build & Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm install

      - name: Build (Next.js static export)
        run: npm run build

      - name: Deploy via FTP (to cPanel public_html)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.CPANEL_FTP_SERVER }}
          username: ${{ secrets.CPANEL_FTP_USERNAME }}
          password: ${{ secrets.CPANEL_FTP_PASSWORD }}
          protocol: ftps
          port: ${{ secrets.CPANEL_FTP_PORT || 21 }}
          local-dir: ./out/
          server-dir: /public_html/
          dangerous-clean-slate: true
          timeout: 600000
