name: Build & Deploy (Static to cPanel)

on:
  push:
    branches: [ main ]   # deploy whenever you push to main
  workflow_dispatch:      # allow manual runs from the Actions tab

concurrency:
  group: deploy-static
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm install

      - name: Build Next.js static export
        run: npm run build
        # your package.json should run: next build && next export
        # output goes to ./out/

      - name: Deploy via FTPS to cPanel public_html
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.faef.se
          username: faefse
          password: l(S9S8D(Yti9o3
          protocol: ftps
          port: 21
          local-dir: ./out/
          server-dir: /public_html/
          dangerous-clean-slate: true   # wipes remote dir before upload (safe for static sites)
          timeout: 600000               # 10 minutes
